SHELL := /bin/bash

ifneq (,$(wildcard .env))
include .env
export
endif

PORT ?= 8080
LLM_RUNTIME ?= local
LLM_BASE_URL ?= http://$(LLAMACPP_HOST):$(LLAMACPP_PORT)/v1
LLM_MODEL ?= gemma4:31b
EVO_X2_TAILNET_HOST ?= evo-x2.tailb30e58.ts.net
EVO_X2_SSH_HOST ?= evo-x2
EVO_X2_SSH_LOCAL_PORT ?= 21434
EVO_X2_OLLAMA_LLM_BASE_URL ?= http://$(EVO_X2_TAILNET_HOST)/v1
EVO_X2_LLAMA_CPP_LLM_BASE_URL ?= http://$(EVO_X2_TAILNET_HOST)/llama/v1
EVO_X2_LLM_BASE_URL ?= $(EVO_X2_OLLAMA_LLM_BASE_URL)
EVO_X2_SSH_LLM_BASE_URL ?= http://127.0.0.1:$(EVO_X2_SSH_LOCAL_PORT)/v1
EVO_X2_LLM_MODEL ?= gemma4:31b
EVO_X2_BRIEF_LLM_MODEL ?= qwen3.6:27b
EVO_X2_STYLE_LLM_MODEL ?= gemma4:e2b
EVO_X2_ARTICLE_LLM_MODEL ?= gemma4:e2b
EVO_X2_DRAFT_LLM_MODEL ?= gemma4:31b
EVO_X2_VERIFY_LLM_MODEL ?= gemma4:latest
FALLBACK_LLM_BASE_URL ?= http://127.0.0.1:8081/v1
LLM_FALLBACK_BASE_URLS ?= $(EVO_X2_LLAMA_CPP_LLM_BASE_URL),$(FALLBACK_LLM_BASE_URL)
EVO_X2_LLAMA_CPP_MODEL ?= gemma-4-E2B-it-Q8_0.gguf
STYLE_LLM_FALLBACK_MODELS ?= $(EVO_X2_LLAMA_CPP_MODEL),gemma4:e2b
BRIEF_LLM_FALLBACK_MODELS ?= $(EVO_X2_LLAMA_CPP_MODEL),qwen3:30b-a3b
ARTICLE_LLM_FALLBACK_MODELS ?= $(EVO_X2_LLAMA_CPP_MODEL),gemma4:e2b
DRAFT_LLM_FALLBACK_MODELS ?= $(EVO_X2_LLAMA_CPP_MODEL),qwen3:30b-a3b
VERIFY_LLM_FALLBACK_MODELS ?= $(EVO_X2_LLAMA_CPP_MODEL),gemma4:e2b
LLAMACPP_HOST ?= 127.0.0.1
LLAMACPP_PORT ?= 8081
LLAMACPP_BASE_URL ?= $(LLM_BASE_URL)
LLAMACPP_MODEL ?= gemma4:31b
LLAMACPP_HF_REPO ?= ggml-org/gemma-4-31B-it-GGUF
LLAMACPP_HF_FILE ?= gemma-4-31B-it-Q4_K_M.gguf
LLAMA_SERVER ?= llama-server

.PHONY: app dev evo-x2 remote evo-x2-preflight evo-x2-models evo-x2-ssh-models scenario-evo-x2 server llama check

app: dev

dev:
	./scripts/dev.sh

evo-x2: remote

remote: evo-x2-preflight
	NOTE_MAKER_SKIP_ENV=1 LLM_RUNTIME=remote LLM_BASE_URL="$(EVO_X2_LLM_BASE_URL)" LLM_MODEL="$(EVO_X2_LLM_MODEL)" STYLE_LLM_MODEL="$(EVO_X2_STYLE_LLM_MODEL)" BRIEF_LLM_MODEL="$(EVO_X2_BRIEF_LLM_MODEL)" ARTICLE_LLM_MODEL="$(EVO_X2_ARTICLE_LLM_MODEL)" DRAFT_LLM_MODEL="$(EVO_X2_DRAFT_LLM_MODEL)" VERIFY_LLM_MODEL="$(EVO_X2_VERIFY_LLM_MODEL)" LLM_FALLBACK_BASE_URLS="$(LLM_FALLBACK_BASE_URLS)" STYLE_LLM_FALLBACK_MODELS="$(STYLE_LLM_FALLBACK_MODELS)" BRIEF_LLM_FALLBACK_MODELS="$(BRIEF_LLM_FALLBACK_MODELS)" ARTICLE_LLM_FALLBACK_MODELS="$(ARTICLE_LLM_FALLBACK_MODELS)" DRAFT_LLM_FALLBACK_MODELS="$(DRAFT_LLM_FALLBACK_MODELS)" VERIFY_LLM_FALLBACK_MODELS="$(VERIFY_LLM_FALLBACK_MODELS)" ./scripts/dev.sh

evo-x2-preflight:
	EVO_X2_TAILNET_HOST="$(EVO_X2_TAILNET_HOST)" EVO_X2_LLM_BASE_URL="$(EVO_X2_LLM_BASE_URL)" ./scripts/evo-x2-tailnet-preflight.sh

evo-x2-models: evo-x2-preflight
	curl -s "$(EVO_X2_LLM_BASE_URL)/models"

evo-x2-ssh-models:
	EVO_X2_SSH_HOST="$(EVO_X2_SSH_HOST)" EVO_X2_SSH_LOCAL_PORT="$(EVO_X2_SSH_LOCAL_PORT)" EVO_X2_LLM_BASE_URL="$(EVO_X2_SSH_LLM_BASE_URL)" ./scripts/evo-x2-ssh-preflight.sh
	curl -s "$(EVO_X2_SSH_LLM_BASE_URL)/models"

scenario-evo-x2: evo-x2-preflight
	RUN_NOTE_SCENARIO=1 RUN_LOCAL_LLM_SCENARIO=1 SCENARIO_STREAM_DRAFT=1 LLM_BASE_URL="$(EVO_X2_LLM_BASE_URL)" LLM_MODEL="$(EVO_X2_LLM_MODEL)" STYLE_LLM_MODEL="$(EVO_X2_STYLE_LLM_MODEL)" BRIEF_LLM_MODEL="$(EVO_X2_BRIEF_LLM_MODEL)" ARTICLE_LLM_MODEL="$(EVO_X2_ARTICLE_LLM_MODEL)" DRAFT_LLM_MODEL="$(EVO_X2_DRAFT_LLM_MODEL)" VERIFY_LLM_MODEL="$(EVO_X2_VERIFY_LLM_MODEL)" LLM_TIMEOUT_SECONDS=900 LLM_FALLBACK_BASE_URLS="$(LLM_FALLBACK_BASE_URLS)" STYLE_LLM_FALLBACK_MODELS="$(STYLE_LLM_FALLBACK_MODELS)" BRIEF_LLM_FALLBACK_MODELS="$(BRIEF_LLM_FALLBACK_MODELS)" ARTICLE_LLM_FALLBACK_MODELS="$(ARTICLE_LLM_FALLBACK_MODELS)" DRAFT_LLM_FALLBACK_MODELS="$(DRAFT_LLM_FALLBACK_MODELS)" VERIFY_LLM_FALLBACK_MODELS="$(VERIFY_LLM_FALLBACK_MODELS)" SCENARIO_MIN_STYLE_SCORE=80 SCENARIO_MIN_DRAFT_RUNES=2800 DRAFT_MAX_ATTEMPTS=2 go run ./cmd/scenario/full_workflow

server:
	go run ./cmd/server

llama:
	$(LLAMA_SERVER) \
		--hf-repo $(LLAMACPP_HF_REPO) \
		--hf-file $(LLAMACPP_HF_FILE) \
		--alias $(LLAMACPP_MODEL) \
		--host $(LLAMACPP_HOST) \
		--port $(LLAMACPP_PORT)

check:
	go test ./...
