SHELL := /bin/bash

ifneq (,$(wildcard .env))
include .env
export
endif

PORT ?= 8080
EVO_X2_TAILNET_HOST ?= evo-x2.tailb30e58.ts.net
EVO_X2_SSH_HOST ?= evo-x2
EVO_X2_SSH_LOCAL_PORT ?= 21434
EVO_X2_OLLAMA_LLM_BASE_URL ?= http://$(EVO_X2_TAILNET_HOST)/v1
EVO_X2_LLAMA_CPP_LLM_BASE_URL ?= http://$(EVO_X2_TAILNET_HOST)/llama/v1
EVO_X2_LLAMA_CPP_SERVICE ?= note-maker-llama-cpp.service
EVO_X2_LLAMA_CPP_PROFILE ?= fallback-gemma-e2b
EVO_X2_LLAMA_CPP_APPLY ?= 0
EVO_X2_LLAMA_CPP_ALLOW_RESTART ?= 0
LLAMA_SWAP_CONFIG ?= deploy/llama-swap/evo-x2.example.yaml
APPLY ?= $(EVO_X2_LLAMA_CPP_APPLY)
ALLOW_RESTART ?= $(EVO_X2_LLAMA_CPP_ALLOW_RESTART)
EVO_X2_LLM_BASE_URL ?= $(EVO_X2_OLLAMA_LLM_BASE_URL)
EVO_X2_SSH_LLM_BASE_URL ?= http://127.0.0.1:$(EVO_X2_SSH_LOCAL_PORT)/v1
LLM_RUNTIME ?= remote
LLM_BASE_URL ?= $(EVO_X2_LLM_BASE_URL)
LLM_MODEL ?= gemma4:31b
EVO_X2_LLM_MODEL ?= gemma4:31b
EVO_X2_BRIEF_LLM_MODEL ?= qwen3.6:27b
EVO_X2_STYLE_LLM_MODEL ?= gemma4:e2b
EVO_X2_ARTICLE_LLM_MODEL ?= gemma4:e2b
EVO_X2_DRAFT_LLM_MODEL ?= gemma4:31b
EVO_X2_VERIFY_LLM_MODEL ?= gemma4:latest
FALLBACK_LLM_BASE_URL ?= http://127.0.0.1:8081/v1
LLM_FALLBACK_BASE_URLS ?= $(EVO_X2_LLAMA_CPP_LLM_BASE_URL),$(FALLBACK_LLM_BASE_URL)
EVO_X2_LLAMA_CPP_MODEL ?= gemma-4-E2B-it-Q8_0.gguf
EVO_X2_LLAMA_CPP_STYLE_MODEL ?= $(EVO_X2_LLAMA_CPP_MODEL)
EVO_X2_LLAMA_CPP_BRIEF_MODEL ?= $(EVO_X2_LLAMA_CPP_MODEL)
EVO_X2_LLAMA_CPP_ARTICLE_MODEL ?= $(EVO_X2_LLAMA_CPP_MODEL)
EVO_X2_LLAMA_CPP_DRAFT_MODEL ?= $(EVO_X2_LLAMA_CPP_MODEL)
EVO_X2_LLAMA_CPP_VERIFY_MODEL ?= $(EVO_X2_LLAMA_CPP_MODEL)
STYLE_LLM_FALLBACK_MODELS ?= $(EVO_X2_LLAMA_CPP_MODEL),gemma4:e2b
BRIEF_LLM_FALLBACK_MODELS ?= $(EVO_X2_LLAMA_CPP_MODEL),qwen3:30b-a3b
ARTICLE_LLM_FALLBACK_MODELS ?= $(EVO_X2_LLAMA_CPP_MODEL),gemma4:e2b
DRAFT_LLM_FALLBACK_MODELS ?= $(EVO_X2_LLAMA_CPP_MODEL),qwen3:30b-a3b
VERIFY_LLM_FALLBACK_MODELS ?= $(EVO_X2_LLAMA_CPP_MODEL),gemma4:e2b
LLM_STREAM_FIRST_BYTE_TIMEOUT_SECONDS ?= 45
LLM_STREAM_IDLE_TIMEOUT_SECONDS ?= 45
LLAMACPP_HOST ?= 127.0.0.1
LLAMACPP_PORT ?= 8081
LLAMACPP_BASE_URL ?= $(LLM_BASE_URL)
LLAMACPP_MODEL ?= gemma4:31b
LLAMACPP_HF_REPO ?= ggml-org/gemma-4-31B-it-GGUF
LLAMACPP_HF_FILE ?= gemma-4-31B-it-Q4_K_M.gguf
LOCAL_LLAMACPP_FALLBACK_BASE_URL ?= http://127.0.0.1:8081/v1
LOCAL_LLAMACPP_FALLBACK_MODEL ?= qwen3:30b-a3b
LOCAL_LLAMACPP_FALLBACK_VERIFY_MODEL ?= $(LOCAL_LLAMACPP_FALLBACK_MODEL)
LOCAL_LLAMACPP_FALLBACK_LOAD_FLAGS ?=
LOCAL_LLAMACPP_FALLBACK_OUTPUT_DIR ?= tmp/local_llamacpp_fallback
LOCAL_LLAMACPP_FALLBACK_MIN_STYLE_SCORE ?= 82
LOCAL_LLAMACPP_FALLBACK_MIN_KEYWORD_OVERLAP ?= 70
LOCAL_LLAMACPP_FALLBACK_MIN_DRAFT_RUNES ?= 2800
LOCAL_LLAMACPP_FALLBACK_TIMEOUT_SECONDS ?= 900
LOCAL_LLAMACPP_FALLBACK_MAX_ATTEMPTS ?= 2
LLAMA_SERVER ?= llama-server
WAILS ?= wails
WAILS_VERSION ?= v2.12.0
NOTE_MAKER_DESKTOP_ADDR ?= 127.0.0.1:8080

.PHONY: app launcher launcher-local launcher-status launcher-check dev evo-x2 remote evo-x2-preflight evo-x2-models evo-x2-ssh-models evo-x2-llama-status evo-x2-llama-plan evo-x2-llama-start evo-x2-llama-swap evo-x2-llama-check scenario-evo-x2 scenario-evo-x2-llama-brief-draft scenario-evo-x2-llama-swap-brief-draft scenario-evo-x2-llama-swap-media-matrix scenario-local-llamacpp-fallback scenario-media-matrix-live server desktop-assets desktop-preview desktop-check desktop-dev desktop-build llama docker-build docker-run docker-compose-up docker-compose-down check e2e

app: launcher

launcher:
	./scripts/launcher.sh

launcher-local:
	NOTE_MAKER_START_LOCAL_LLM=1 ./scripts/launcher.sh --local-llm

launcher-status:
	./scripts/launcher.sh --status

launcher-check:
	./scripts/check-launcher.sh

dev:
	./scripts/dev.sh

evo-x2: remote

remote: evo-x2-preflight
	NOTE_MAKER_SKIP_ENV=1 LLM_RUNTIME=remote LLM_BASE_URL="$(EVO_X2_LLM_BASE_URL)" LLM_MODEL="$(EVO_X2_LLM_MODEL)" STYLE_LLM_MODEL="$(EVO_X2_STYLE_LLM_MODEL)" BRIEF_LLM_MODEL="$(EVO_X2_BRIEF_LLM_MODEL)" ARTICLE_LLM_MODEL="$(EVO_X2_ARTICLE_LLM_MODEL)" DRAFT_LLM_MODEL="$(EVO_X2_DRAFT_LLM_MODEL)" VERIFY_LLM_MODEL="$(EVO_X2_VERIFY_LLM_MODEL)" LLM_FALLBACK_BASE_URLS="$(LLM_FALLBACK_BASE_URLS)" STYLE_LLM_FALLBACK_MODELS="$(STYLE_LLM_FALLBACK_MODELS)" BRIEF_LLM_FALLBACK_MODELS="$(BRIEF_LLM_FALLBACK_MODELS)" ARTICLE_LLM_FALLBACK_MODELS="$(ARTICLE_LLM_FALLBACK_MODELS)" DRAFT_LLM_FALLBACK_MODELS="$(DRAFT_LLM_FALLBACK_MODELS)" VERIFY_LLM_FALLBACK_MODELS="$(VERIFY_LLM_FALLBACK_MODELS)" ./scripts/dev.sh

evo-x2-preflight:
	EVO_X2_TAILNET_HOST="$(EVO_X2_TAILNET_HOST)" EVO_X2_LLM_BASE_URL="$(EVO_X2_LLM_BASE_URL)" ./scripts/evo-x2-tailnet-preflight.sh

evo-x2-models: evo-x2-preflight
	curl -s "$(EVO_X2_LLM_BASE_URL)/models"

evo-x2-ssh-models:
	EVO_X2_SSH_HOST="$(EVO_X2_SSH_HOST)" EVO_X2_SSH_LOCAL_PORT="$(EVO_X2_SSH_LOCAL_PORT)" EVO_X2_LLM_BASE_URL="$(EVO_X2_SSH_LLM_BASE_URL)" ./scripts/evo-x2-ssh-preflight.sh
	curl -s "$(EVO_X2_SSH_LLM_BASE_URL)/models"

evo-x2-llama-status:
	@echo "Manual diagnostic: legacy systemd profile path. llama-swap adoption uses evo-x2-llama-check and live-gated scenario targets."
	EVO_X2_TAILNET_HOST="$(EVO_X2_TAILNET_HOST)" EVO_X2_SSH_HOST="$(EVO_X2_SSH_HOST)" EVO_X2_OLLAMA_LLM_BASE_URL="$(EVO_X2_OLLAMA_LLM_BASE_URL)" EVO_X2_LLAMA_CPP_LLM_BASE_URL="$(EVO_X2_LLAMA_CPP_LLM_BASE_URL)" EVO_X2_LLAMA_CPP_SERVICE="$(EVO_X2_LLAMA_CPP_SERVICE)" EVO_X2_LLAMA_CPP_PROFILE="$(EVO_X2_LLAMA_CPP_PROFILE)" EVO_X2_LLAMA_CPP_APPLY="$(APPLY)" EVO_X2_LLAMA_CPP_ALLOW_RESTART="$(ALLOW_RESTART)" ./scripts/evo-x2-llama-swap.sh inspect

evo-x2-llama-plan:
	@echo "Manual diagnostic: legacy systemd profile path. llama-swap adoption uses evo-x2-llama-check and live-gated scenario targets."
	EVO_X2_TAILNET_HOST="$(EVO_X2_TAILNET_HOST)" EVO_X2_SSH_HOST="$(EVO_X2_SSH_HOST)" EVO_X2_OLLAMA_LLM_BASE_URL="$(EVO_X2_OLLAMA_LLM_BASE_URL)" EVO_X2_LLAMA_CPP_LLM_BASE_URL="$(EVO_X2_LLAMA_CPP_LLM_BASE_URL)" EVO_X2_LLAMA_CPP_SERVICE="$(EVO_X2_LLAMA_CPP_SERVICE)" EVO_X2_LLAMA_CPP_PROFILE="$(EVO_X2_LLAMA_CPP_PROFILE)" EVO_X2_LLAMA_CPP_APPLY="$(APPLY)" EVO_X2_LLAMA_CPP_ALLOW_RESTART="$(ALLOW_RESTART)" ./scripts/evo-x2-llama-swap.sh plan

evo-x2-llama-start:
	@echo "Manual diagnostic: legacy systemd profile path. This can mutate Evo X2 only with APPLY=1."
	EVO_X2_TAILNET_HOST="$(EVO_X2_TAILNET_HOST)" EVO_X2_SSH_HOST="$(EVO_X2_SSH_HOST)" EVO_X2_OLLAMA_LLM_BASE_URL="$(EVO_X2_OLLAMA_LLM_BASE_URL)" EVO_X2_LLAMA_CPP_LLM_BASE_URL="$(EVO_X2_LLAMA_CPP_LLM_BASE_URL)" EVO_X2_LLAMA_CPP_SERVICE="$(EVO_X2_LLAMA_CPP_SERVICE)" EVO_X2_LLAMA_CPP_PROFILE="$(EVO_X2_LLAMA_CPP_PROFILE)" EVO_X2_LLAMA_CPP_APPLY="$(APPLY)" EVO_X2_LLAMA_CPP_ALLOW_RESTART="$(ALLOW_RESTART)" ./scripts/evo-x2-llama-swap.sh start

evo-x2-llama-swap:
	@echo "Manual diagnostic: legacy systemd profile path. This can mutate Evo X2 only with APPLY=1 ALLOW_RESTART=1."
	EVO_X2_TAILNET_HOST="$(EVO_X2_TAILNET_HOST)" EVO_X2_SSH_HOST="$(EVO_X2_SSH_HOST)" EVO_X2_OLLAMA_LLM_BASE_URL="$(EVO_X2_OLLAMA_LLM_BASE_URL)" EVO_X2_LLAMA_CPP_LLM_BASE_URL="$(EVO_X2_LLAMA_CPP_LLM_BASE_URL)" EVO_X2_LLAMA_CPP_SERVICE="$(EVO_X2_LLAMA_CPP_SERVICE)" EVO_X2_LLAMA_CPP_PROFILE="$(EVO_X2_LLAMA_CPP_PROFILE)" EVO_X2_LLAMA_CPP_APPLY="$(APPLY)" EVO_X2_LLAMA_CPP_ALLOW_RESTART="$(ALLOW_RESTART)" ./scripts/evo-x2-llama-swap.sh swap

evo-x2-llama-check:
	bash -n scripts/dev.sh scripts/evo-x2-tailnet-preflight.sh scripts/evo-x2-ssh-preflight.sh scripts/evo-x2-llama-swap.sh
	LLAMA_SWAP_CONFIG="$(LLAMA_SWAP_CONFIG)" APPLY=0 ALLOW_RESTART=0 EVO_X2_LLAMA_CPP_APPLY=0 EVO_X2_LLAMA_CPP_ALLOW_RESTART=0 ./scripts/evo-x2-llama-swap.sh validate

scenario-evo-x2: evo-x2-preflight
	RUN_NOTE_SCENARIO=1 RUN_LOCAL_LLM_SCENARIO=1 SCENARIO_STREAM_DRAFT=1 LLM_BASE_URL="$(EVO_X2_LLM_BASE_URL)" LLM_MODEL="$(EVO_X2_LLM_MODEL)" STYLE_LLM_MODEL="$(EVO_X2_STYLE_LLM_MODEL)" BRIEF_LLM_MODEL="$(EVO_X2_BRIEF_LLM_MODEL)" ARTICLE_LLM_MODEL="$(EVO_X2_ARTICLE_LLM_MODEL)" DRAFT_LLM_MODEL="$(EVO_X2_DRAFT_LLM_MODEL)" VERIFY_LLM_MODEL="$(EVO_X2_VERIFY_LLM_MODEL)" LLM_TIMEOUT_SECONDS=900 LLM_STREAM_FIRST_BYTE_TIMEOUT_SECONDS="$(LLM_STREAM_FIRST_BYTE_TIMEOUT_SECONDS)" LLM_STREAM_IDLE_TIMEOUT_SECONDS="$(LLM_STREAM_IDLE_TIMEOUT_SECONDS)" LLM_FALLBACK_BASE_URLS="$(LLM_FALLBACK_BASE_URLS)" STYLE_LLM_FALLBACK_MODELS="$(STYLE_LLM_FALLBACK_MODELS)" BRIEF_LLM_FALLBACK_MODELS="$(BRIEF_LLM_FALLBACK_MODELS)" ARTICLE_LLM_FALLBACK_MODELS="$(ARTICLE_LLM_FALLBACK_MODELS)" DRAFT_LLM_FALLBACK_MODELS="$(DRAFT_LLM_FALLBACK_MODELS)" VERIFY_LLM_FALLBACK_MODELS="$(VERIFY_LLM_FALLBACK_MODELS)" SCENARIO_MIN_STYLE_SCORE=80 SCENARIO_MIN_DRAFT_RUNES=2800 DRAFT_MAX_ATTEMPTS=2 go run ./cmd/scenario/full_workflow

scenario-evo-x2-llama-brief-draft:
	@if [ "$${RUN_EVO_X2_LLAMA_CPP_SCENARIO:-0}" != "1" ]; then echo "Set RUN_EVO_X2_LLAMA_CPP_SCENARIO=1 to run the live Evo X2 llama.cpp brief/draft validation."; exit 2; fi
	EVO_X2_TAILNET_HOST="$(EVO_X2_TAILNET_HOST)" EVO_X2_LLM_BASE_URL="$(EVO_X2_LLAMA_CPP_LLM_BASE_URL)" ./scripts/evo-x2-tailnet-preflight.sh
	RUN_NOTE_SCENARIO=1 RUN_LOCAL_LLM_SCENARIO=1 SCENARIO_STREAM_DRAFT=1 LLM_BASE_URL="$(EVO_X2_LLAMA_CPP_LLM_BASE_URL)" LLM_MODEL="$(EVO_X2_LLAMA_CPP_MODEL)" STYLE_LLM_MODEL="$(EVO_X2_LLAMA_CPP_STYLE_MODEL)" BRIEF_LLM_MODEL="$(EVO_X2_LLAMA_CPP_BRIEF_MODEL)" ARTICLE_LLM_MODEL="$(EVO_X2_LLAMA_CPP_ARTICLE_MODEL)" DRAFT_LLM_MODEL="$(EVO_X2_LLAMA_CPP_DRAFT_MODEL)" VERIFY_LLM_MODEL="$(EVO_X2_LLAMA_CPP_VERIFY_MODEL)" LLM_TIMEOUT_SECONDS=900 LLM_STREAM_FIRST_BYTE_TIMEOUT_SECONDS="$(LLM_STREAM_FIRST_BYTE_TIMEOUT_SECONDS)" LLM_STREAM_IDLE_TIMEOUT_SECONDS="$(LLM_STREAM_IDLE_TIMEOUT_SECONDS)" LLM_FALLBACK_BASE_URLS="" STYLE_LLM_FALLBACK_MODELS="" BRIEF_LLM_FALLBACK_MODELS="" ARTICLE_LLM_FALLBACK_MODELS="" DRAFT_LLM_FALLBACK_MODELS="" VERIFY_LLM_FALLBACK_MODELS="" SCENARIO_MIN_STYLE_SCORE=80 SCENARIO_MIN_DRAFT_RUNES=2800 DRAFT_MAX_ATTEMPTS=2 go run ./cmd/scenario/full_workflow

scenario-evo-x2-llama-swap-brief-draft:
	@if [ "$${RUN_EVO_X2_LLAMA_SWAP_SCENARIO:-0}" != "1" ]; then echo "Set RUN_EVO_X2_LLAMA_SWAP_SCENARIO=1 to run the live Evo X2 llama-swap 3-model validation."; exit 2; fi
	EVO_X2_TAILNET_HOST="$(EVO_X2_TAILNET_HOST)" EVO_X2_LLM_BASE_URL="$(EVO_X2_LLAMA_CPP_LLM_BASE_URL)" ./scripts/evo-x2-tailnet-preflight.sh
	RUN_NOTE_SCENARIO=1 RUN_LOCAL_LLM_SCENARIO=1 SCENARIO_STREAM_DRAFT=1 LLM_BASE_URL="$(EVO_X2_LLAMA_CPP_LLM_BASE_URL)" LLM_MODEL="gemma4:31b" STYLE_LLM_MODEL="gemma4:e2b" BRIEF_LLM_MODEL="qwen3.6:27b" ARTICLE_LLM_MODEL="gemma4:e2b" DRAFT_LLM_MODEL="gemma4:31b" VERIFY_LLM_MODEL="gemma4:31b" LLM_TIMEOUT_SECONDS=900 LLM_STREAM_FIRST_BYTE_TIMEOUT_SECONDS=8 LLM_STREAM_IDLE_TIMEOUT_SECONDS="$(LLM_STREAM_IDLE_TIMEOUT_SECONDS)" LLM_FALLBACK_BASE_URLS="" STYLE_LLM_FALLBACK_MODELS="" BRIEF_LLM_FALLBACK_MODELS="" ARTICLE_LLM_FALLBACK_MODELS="" DRAFT_LLM_FALLBACK_MODELS="" VERIFY_LLM_FALLBACK_MODELS="" SCENARIO_MIN_STYLE_SCORE=82 SCENARIO_MIN_KEYWORD_OVERLAP=70 SCENARIO_MAX_FIRST_CHUNK_MS=8000 SCENARIO_MIN_DRAFT_RUNES=2800 DRAFT_MAX_ATTEMPTS=2 go run ./cmd/scenario/full_workflow

scenario-evo-x2-llama-swap-media-matrix:
	@if [ "$${RUN_EVO_X2_LLAMA_SWAP_MEDIA_MATRIX:-0}" != "1" ]; then echo "Set RUN_EVO_X2_LLAMA_SWAP_MEDIA_MATRIX=1 to run the live Evo X2 llama-swap 5-format fallback-only matrix."; exit 2; fi
	SCENARIO_OUTPUT_DIR=tmp/media_matrix go run ./cmd/scenario/media_matrix
	RUN_LIVE_MEDIA_MATRIX=1 LIVE_MEDIA_MATRIX_CASES="terisuke_note_essay,cor_blog_technical_report,cor_blog_vision_sharing,cloudia_zenn_tutorial,cloudia_qiita_how_to,cor_homepage_section" SCENARIO_STREAM_DRAFT=1 SCENARIO_OUTPUT_DIR=tmp/media_matrix LIVE_MEDIA_MATRIX_OUTPUT_DIR=tmp/media_matrix/llama_swap LLM_BASE_URL="$(EVO_X2_LLAMA_CPP_LLM_BASE_URL)" LLM_MODEL="gemma4:31b" STYLE_LLM_MODEL="gemma4:e2b" BRIEF_LLM_MODEL="qwen3.6:27b" ARTICLE_LLM_MODEL="gemma4:e2b" DRAFT_LLM_MODEL="gemma4:31b" VERIFY_LLM_MODEL="gemma4:31b" LLM_TIMEOUT_SECONDS=900 LLM_STREAM_FIRST_BYTE_TIMEOUT_SECONDS=8 LLM_STREAM_IDLE_TIMEOUT_SECONDS="$(LLM_STREAM_IDLE_TIMEOUT_SECONDS)" LLM_FALLBACK_BASE_URLS="" STYLE_LLM_FALLBACK_MODELS="" BRIEF_LLM_FALLBACK_MODELS="" ARTICLE_LLM_FALLBACK_MODELS="" DRAFT_LLM_FALLBACK_MODELS="" VERIFY_LLM_FALLBACK_MODELS="" SCENARIO_MIN_STYLE_SCORE=82 SCENARIO_MIN_KEYWORD_OVERLAP=70 SCENARIO_MAX_FIRST_CHUNK_MS=8000 DRAFT_MAX_ATTEMPTS=2 go run ./cmd/scenario/live_media_matrix

scenario-local-llamacpp-fallback:
	LOCAL_LLAMACPP_FALLBACK_BASE_URL="$(LOCAL_LLAMACPP_FALLBACK_BASE_URL)" LOCAL_LLAMACPP_FALLBACK_MODEL="$(LOCAL_LLAMACPP_FALLBACK_MODEL)" LOCAL_LLAMACPP_FALLBACK_VERIFY_MODEL="$(LOCAL_LLAMACPP_FALLBACK_VERIFY_MODEL)" LOCAL_LLAMACPP_FALLBACK_LOAD_FLAGS="$(LOCAL_LLAMACPP_FALLBACK_LOAD_FLAGS)" LOCAL_LLAMACPP_FALLBACK_OUTPUT_DIR="$(LOCAL_LLAMACPP_FALLBACK_OUTPUT_DIR)" LOCAL_LLAMACPP_FALLBACK_MIN_STYLE_SCORE="$(LOCAL_LLAMACPP_FALLBACK_MIN_STYLE_SCORE)" LOCAL_LLAMACPP_FALLBACK_MIN_KEYWORD_OVERLAP="$(LOCAL_LLAMACPP_FALLBACK_MIN_KEYWORD_OVERLAP)" LOCAL_LLAMACPP_FALLBACK_MIN_DRAFT_RUNES="$(LOCAL_LLAMACPP_FALLBACK_MIN_DRAFT_RUNES)" LOCAL_LLAMACPP_FALLBACK_TIMEOUT_SECONDS="$(LOCAL_LLAMACPP_FALLBACK_TIMEOUT_SECONDS)" LOCAL_LLAMACPP_FALLBACK_MAX_ATTEMPTS="$(LOCAL_LLAMACPP_FALLBACK_MAX_ATTEMPTS)" go run ./cmd/scenario/local_llamacpp_fallback

scenario-media-matrix-live: evo-x2-preflight
	SCENARIO_OUTPUT_DIR=tmp/media_matrix go run ./cmd/scenario/media_matrix
	RUN_LIVE_MEDIA_MATRIX=1 SCENARIO_STREAM_DRAFT=1 SCENARIO_OUTPUT_DIR=tmp/media_matrix LIVE_MEDIA_MATRIX_OUTPUT_DIR=tmp/media_matrix/live LLM_BASE_URL="$(EVO_X2_LLM_BASE_URL)" LLM_MODEL="$(EVO_X2_LLM_MODEL)" STYLE_LLM_MODEL="$(EVO_X2_STYLE_LLM_MODEL)" BRIEF_LLM_MODEL="$(EVO_X2_BRIEF_LLM_MODEL)" ARTICLE_LLM_MODEL="$(EVO_X2_ARTICLE_LLM_MODEL)" DRAFT_LLM_MODEL="$(EVO_X2_DRAFT_LLM_MODEL)" VERIFY_LLM_MODEL="$(EVO_X2_VERIFY_LLM_MODEL)" LLM_TIMEOUT_SECONDS=900 LLM_STREAM_FIRST_BYTE_TIMEOUT_SECONDS="$(LLM_STREAM_FIRST_BYTE_TIMEOUT_SECONDS)" LLM_STREAM_IDLE_TIMEOUT_SECONDS="$(LLM_STREAM_IDLE_TIMEOUT_SECONDS)" LLM_FALLBACK_BASE_URLS="$(LLM_FALLBACK_BASE_URLS)" STYLE_LLM_FALLBACK_MODELS="$(STYLE_LLM_FALLBACK_MODELS)" BRIEF_LLM_FALLBACK_MODELS="$(BRIEF_LLM_FALLBACK_MODELS)" ARTICLE_LLM_FALLBACK_MODELS="$(ARTICLE_LLM_FALLBACK_MODELS)" DRAFT_LLM_FALLBACK_MODELS="$(DRAFT_LLM_FALLBACK_MODELS)" VERIFY_LLM_FALLBACK_MODELS="$(VERIFY_LLM_FALLBACK_MODELS)" SCENARIO_MIN_STYLE_SCORE=80 SCENARIO_MIN_DRAFT_RUNES=1400 DRAFT_MAX_ATTEMPTS=2 go run ./cmd/scenario/live_media_matrix

server:
	go run ./cmd/server

desktop-assets:
	rsync -a --delete --exclude 'history_ui_test.go' --exclude 'vendor/' static/ cmd/desktop/frontend/
	rm -rf cmd/desktop/frontend/_vendor
	mkdir -p cmd/desktop/frontend/_vendor
	rsync -a static/vendor/ cmd/desktop/frontend/_vendor/

desktop-preview: desktop-assets
	NOTE_MAKER_DESKTOP_ADDR="$(NOTE_MAKER_DESKTOP_ADDR)" go run ./cmd/desktop

desktop-check: desktop-assets
	(cd cmd/desktop && go list -m github.com/wailsapp/wails/v2 | grep -q '$(WAILS_VERSION)$$')
	(cd cmd/desktop && go test -tags wails ./...)

desktop-dev: desktop-check
	(cd cmd/desktop && go run github.com/wailsapp/wails/v2/cmd/wails@$(WAILS_VERSION) dev)

desktop-build: desktop-check
	(cd cmd/desktop && go run github.com/wailsapp/wails/v2/cmd/wails@$(WAILS_VERSION) build)

llama:
	$(LLAMA_SERVER) \
		--hf-repo $(LLAMACPP_HF_REPO) \
		--hf-file $(LLAMACPP_HF_FILE) \
		--alias $(LLAMACPP_MODEL) \
		--host $(LLAMACPP_HOST) \
		--port $(LLAMACPP_PORT)

docker-build:
	docker build -t note-maker:dev .

docker-run: docker-build
	docker run --rm -p $(PORT):8080 note-maker:dev

docker-compose-up:
	docker compose up -d --build

docker-compose-down:
	docker compose down

check:
	go test ./...

e2e:
	python3 -m pytest tests/e2e
